# Generated by Django 5.2.8 on 2025-11-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='favorite_game',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='game_gender',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='playing_hours',
            field=models.IntegerField(null=True),
        ),
    ]
